
version: 2

models:
  - name: analysis_yt_data
    description: "analysis dbt model"
    columns:
      - name: genre
        description: "genre of yt channel"
        tests:
          - unique
          - not_null

  - name: yt_model
    description: "transformation dbt model"
    columns:
      - name: genre
        description: "genre of yt channel"
        tests:
          - unique
          - not_null
