dbt_demo:
  outputs:
    dev:
      account: wquvqrj-az75828
      database: DEMO
      password: P#ssw0rd
      role: ACCOUNTADMIN
      schema: DEMO_03142023
      threads: 10
      type: snowflake
      user: AvishkaHashenu
      warehouse: COMPUTE_WH
  target: dev
dbt_project:
  outputs:
    dev:
      account: wquvqrj-az75828
      database: DEMO
      password: P#ssw0rd
      role: ACCOUNTADMIN
      schema: DEMO_03142023_DEMO_03142023
      threads: 10
      type: snowflake
      user: AvishkaHashenu
      warehouse: COMPUTE_WH
      
    prod:
      account: wquvqrj-az75828
      database: DEMO
      password: P#ssw0rd
      role: ACCOUNTADMIN
      schema: DEMO_03142023_DEMO_03142023
      threads: 10
      type: snowflake
      user: AvishkaHashenu
      warehouse: COMPUTE_WH
  target: dev
  
